In [1]:
import numpy
numpy.__version__

'1.20.1'

In [3]:
# Numpy is typically installed using np as an alias

import numpy as np
np.__version__

'1.20.1'

In [4]:
# Python is a dynamically typed language so object types dont need to be explicitly declared

result = 1
print(type(result))

<class 'int'>


In [5]:
# dynamic typing is flexible but less efficient

x = 4
x = "four"
print(type(x))

<class 'str'>


In [7]:
# lists contain many Python variables so this inefficiency stacks on top of itself

L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
type(L[0])

int

In [9]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [10]:
type(L2[0])

str

In [12]:
# dynamic typing allows for flexible heterogeneous lists

L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [13]:
# most lists are homogenous in type and Numpy will minimize redundancy of metadata

import numpy as np
np.__version__

'1.20.1'

In [14]:
# can create a single object type array from Python lists

np.array(L)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# all object types in a Numpy array will be of the same type

np.array([3.14, 1, 2])

# Numpy will cast up if possible so everything is the same type

array([3.14, 1.  , 2.  ])

In [16]:
# can make multi dimentional arrays

np.array ([range(i, i + 3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [17]:
# its most efficient to use built in Numpy funcitons to make arrays from scratch

np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [22]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
np.linspace(0, 1, 9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])